### ISSUE TITLE
[Ext : themes] Fatal error TYPO3 7.6 

### ISSUE THREAD

**Issue by goumpi** [typo3-themes/themes#120] opened 2015-12-01 17:39 UTC
Hi, 

On Backend theme module i have one error. 

> Fatal error: Call to a member function get() on a non-object in /home/dev/src/typo3_src-7.6.0/typo3/sysext/extensionmanager/Classes/Utility/ConfigurationUtility.php on line 129

To resolve this problem i changed the line 72 on file EditorController.php (Classes/Controller/EditorController.php)

> $extensionConfiguration = $configurationUtility->getCurrentConfiguration('themes');

By

> $extensionConfiguration = unserialize($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['themes']);

**Comment by kaystrobach** [comment] 2015-12-01 17:40
thank you for reporting this is a duplicate of #117 there is a problem in object creation

**Closed** 2015-12-05 15:24 UTC
